name: "coverage"
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: "14"
      - name: Install dependencies for test
        run: |
          cd ./server
          npm install cross-fetch
          cd ..
          npm install 
      - name: Test
        run: npm test -- --coverage
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: ./coverage
